### ISSUE TITLE
What happened to the Batch iconset?

### ISSUE THREAD

**Issue by dodedodo** [AdamWhitcroft/adamwhitcroft.github.io#3]
Hey Adam,

I'm wondering, what happened to the icon set you published all those years ago? It used to be on your website and git. But now, the only thing left seems to be the orphaned git repo on my pc. 

Do you mind if I keep using it?

:slightly_smiling_face:

**Comment by AdamWhitcroft** [comment]
Hey @dodedodo 

If you still have a copy of it, feel free to use it! I shut all of my icon repos down because I had a baby and decided to indefinitely pause all of my side projects (including maintaining and updating icon sets).

Keep well!
